<?php

namespace TricksBundle\Repository;

/**
 * TrickVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
