<?php

namespace ST\TricksBundle\Repository;

/**
 * TrickGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithRelations($relations){

        if(is_string($relations)) {
            $relations = [$relations];
        }

        if (empty($relations)) {
            throw new \InvalidArgumentException('Array that need to contains relations in empty.');
        }

        $qb = $this->createQueryBuilder('tg');

        foreach($relations as $relation) {
            $joinedEntityShortName = substr($relation,0,3);
            $qb->join('tg.'.$relation, $joinedEntityShortName);
            $qb->addSelect($joinedEntityShortName);
        }

        return $qb->getQuery()->getResult();
    }
}
