<?php

namespace ST\TricksBundle\Repository;

/**
 * TrickCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
