<?php

namespace ST\TricksBundle\Repository;

/**
 * TrickGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithTricks(){

        $qb = $this->createQueryBuilder('tg');

        $qb->join('tg.tricks', 'tricks');
        $qb->addSelect('tricks');
        $qb->leftJoin('tricks.photos','tricksPhotos');
        $qb->addSelect('tricksPhotos');
        $qb->leftJoin('tricks.videos','tricksVideos');
        $qb->addSelect('tricksVideos');

        return $qb->getQuery()->getResult();
    }
}
