<?php

namespace ST\TricksBundle\Repository;

/**
 * TrickPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
